### ISSUE TITLE
[Support] Compatibility with Python3.10 

### ISSUE THREAD

**Issue by Henrrypg** [openedx/openedx-events#128]
## Description

Trying to add python3.10 support on [eox-hooks](https://github.com/eduNEXT/eox-hooks) fails due to openedx-events.

### Versions 

- ENV: Python 3.10.6

### Error

```
ERROR: test_receiver_called_after_cert_change (eox_hooks.tests.test_receivers.TestCohortEventsHandler)
Test that hooks_handler is called the correct information after sending
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/edunextdev/Documents/edunext/eox-hooks/env/lib/python3.10/site-packages/django/test/utils.py", line 387, in inner
    return func(*args, **kwargs)
  File "/home/edunextdev/Documents/edunext/eox-hooks/env/lib/python3.10/site-packages/mock/mock.py", line 1346, in patched
    return func(*newargs, **newkeywargs)
  File "/home/edunextdev/Documents/edunext/eox-hooks/eox_hooks/tests/test_receivers.py", line 481, in test_receiver_called_after_cert_change
    COHORT_MEMBERSHIP_CHANGED.send_event(
  File "/home/edunextdev/Documents/edunext/eox-hooks/env/lib/python3.10/site-packages/openedx_events/tooling.py", line 170, in send_event
    format_responses(responses, depth=2),
  File "/home/edunextdev/Documents/edunext/eox-hooks/env/lib/python3.10/site-packages/openedx_events/utils.py", line 90, in format_responses
    ).pformat(obj)
  File "/usr/lib/python3.10/pprint.py", line 157, in pformat
    self._format(object, sio, 0, 0, {}, 0)
  File "/home/edunextdev/Documents/edunext/eox-hooks/env/lib/python3.10/site-packages/openedx_events/utils.py", line 31, in _format
    if isinstance(obj, collections.Callable):
AttributeError: module 'collections' has no attribute 'Callable'

======================================================================
ERROR: test_receiver_called_after_enroll_change (eox_hooks.tests.test_receivers.TestEnrollmentEventsHandler)
Test that hooks_handler is called the correct information after sending
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/edunextdev/Documents/edunext/eox-hooks/env/lib/python3.10/site-packages/django/test/utils.py", line 387, in inner
    return func(*args, **kwargs)
  File "/home/edunextdev/Documents/edunext/eox-hooks/env/lib/python3.10/site-packages/mock/mock.py", line 1346, in patched
    return func(*newargs, **newkeywargs)
  File "/home/edunextdev/Documents/edunext/eox-hooks/eox_hooks/tests/test_receivers.py", line 263, in test_receiver_called_after_enroll_change
    COURSE_ENROLLMENT_CHANGED.send_event(
  File "/home/edunextdev/Documents/edunext/eox-hooks/env/lib/python3.10/site-packages/openedx_events/tooling.py", line 170, in send_event
    format_responses(responses, depth=2),
  File "/home/edunextdev/Documents/edunext/eox-hooks/env/lib/python3.10/site-packages/openedx_events/utils.py", line 90, in format_responses
    ).pformat(obj)
  File "/usr/lib/python3.10/pprint.py", line 157, in pformat
    self._format(object, sio, 0, 0, {}, 0)
  File "/home/edunextdev/Documents/edunext/eox-hooks/env/lib/python3.10/site-packages/openedx_events/utils.py", line 31, in _format
    if isinstance(obj, collections.Callable):
AttributeError: module 'collections' has no attribute 'Callable'

======================================================================
ERROR: test_receiver_called_after_enrollment (eox_hooks.tests.test_receivers.TestEnrollmentEventsHandler)
Test that hooks_handler is called the correct information after sending
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/edunextdev/Documents/edunext/eox-hooks/env/lib/python3.10/site-packages/django/test/utils.py", line 387, in inner
    return func(*args, **kwargs)
  File "/home/edunextdev/Documents/edunext/eox-hooks/env/lib/python3.10/site-packages/mock/mock.py", line 1346, in patched
    return func(*newargs, **newkeywargs)
  File "/home/edunextdev/Documents/edunext/eox-hooks/eox_hooks/tests/test_receivers.py", line 231, in test_receiver_called_after_enrollment
    COURSE_ENROLLMENT_CREATED.send_event(
  File "/home/edunextdev/Documents/edunext/eox-hooks/env/lib/python3.10/site-packages/openedx_events/tooling.py", line 170, in send_event
    format_responses(responses, depth=2),
  File "/home/edunextdev/Documents/edunext/eox-hooks/env/lib/python3.10/site-packages/openedx_events/utils.py", line 90, in format_responses
    ).pformat(obj)
  File "/usr/lib/python3.10/pprint.py", line 157, in pformat
    self._format(object, sio, 0, 0, {}, 0)
  File "/home/edunextdev/Documents/edunext/eox-hooks/env/lib/python3.10/site-packages/openedx_events/utils.py", line 31, in _format
    if isinstance(obj, collections.Callable):
AttributeError: module 'collections' has no attribute 'Callable'

======================================================================
ERROR: test_receiver_called_after_unenrollment (eox_hooks.tests.test_receivers.TestEnrollmentEventsHandler)
Test that hooks_handler is called the correct information after sending
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/edunextdev/Documents/edunext/eox-hooks/env/lib/python3.10/site-packages/django/test/utils.py", line 387, in inner
    return func(*args, **kwargs)
  File "/home/edunextdev/Documents/edunext/eox-hooks/env/lib/python3.10/site-packages/mock/mock.py", line 1346, in patched
    return func(*newargs, **newkeywargs)
  File "/home/edunextdev/Documents/edunext/eox-hooks/eox_hooks/tests/test_receivers.py", line 295, in test_receiver_called_after_unenrollment
    COURSE_UNENROLLMENT_COMPLETED.send_event(
  File "/home/edunextdev/Documents/edunext/eox-hooks/env/lib/python3.10/site-packages/openedx_events/tooling.py", line 170, in send_event
    format_responses(responses, depth=2),
  File "/home/edunextdev/Documents/edunext/eox-hooks/env/lib/python3.10/site-packages/openedx_events/utils.py", line 90, in format_responses
    ).pformat(obj)
  File "/usr/lib/python3.10/pprint.py", line 157, in pformat
    self._format(object, sio, 0, 0, {}, 0)
  File "/home/edunextdev/Documents/edunext/eox-hooks/env/lib/python3.10/site-packages/openedx_events/utils.py", line 31, in _format
    if isinstance(obj, collections.Callable):
AttributeError: module 'collections' has no attribute 'Callable'

```

**Comment by mariajgrimaldi** [comment]
I'll be looking into this issue this week, thanks for the report!

**Comment by mariajgrimaldi** [comment]
Hello again. I've been thinking about this, and I'm not convinced we're ready for it, at least for now. 

Can you specify why we should add support for python 3.10? 

Our latest release should work for the master branch of the services that use openedx-events, which are currently using python 3.8 still. We should focus on maintaining the library without breaking changes since the olive cut is getting closer, and I'm not sure when the community is migrating to Python 3.10., And our primary goal should be not to introduce any bugs when it's not necessary. At least, that's what I think.

@felipemontoya, what are your thoughts on this?

I'll be happy to add it to the CI, the issue that makes me not wanna do it is that we would need to do some refactoring for it to work.

**Comment by felipemontoya** [comment]
I think that adding support for 3.10 is a nice to have. I also would not risk introducing any bugs before the cut is made. But right 
after we are game.

It also looks safe to fix since it appears that the only issue is with the line "if isinstance(obj, collections.Callable)". Which lives in the esponsePrettyPrinter(PrettyPrinter). This import call has been deprecated since python 3.3.

```
~$ python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import collections
>>> collections.Callable
<stdin>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
```
